import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import SwitchTheme from "@/components/switch-theme";
import { NotesProvider } from "../context/NotesContext";
import { TasksProvider } from "../context/TasksContext";
import { ThemeProviders } from "../context/ThemeContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: any) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProviders>
          <TasksProvider>
            <NotesProvider>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
              >
                <header></header>

                {/* FIXED WRAPPER */}
                <div className="flex w-full min-h-screen">
                  {/* <Sidebar /> */}

                  {/* MAIN FIXES EVERYTHING */}
                  <main className="bg-background min-w-0 flex-1 overflow-visible">
                    {children}
                  </main>
                </div>
              </ThemeProvider>
            </NotesProvider>
          </TasksProvider>
        </ThemeProviders>
      </body>
    </html>
  );
}
