import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import SwitchTheme from "@/components/switch-theme";
import { NotesProvider } from "../context/NotesContext";
import { TasksProvider } from "../context/TasksContext";
import { ThemeProviders } from "../context/ThemeContext";
import { CategoryProvider } from "../context/CategoryContext";
import { SessionProvider } from "../context/SessionContext";
import { ActiveTaskProvider } from "../context/ActiveTaskContext";
import SessionWatcher from "../context/SessionWatcher";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: any) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <ThemeProviders>
  <SessionProvider>
    <CategoryProvider>
      <ActiveTaskProvider>

        {/* 👁️ GLOBAL SESSION → TASK LINK */}
        <SessionWatcher />

        <TasksProvider>
          <NotesProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <header></header>

              <div className="flex w-full min-h-screen">
                <main className="bg-background min-w-0 flex-1 overflow-visible">
                  {children}
                </main>
              </div>

            </ThemeProvider>
          </NotesProvider>
        </TasksProvider>

      </ActiveTaskProvider>
    </CategoryProvider>
  </SessionProvider>
</ThemeProviders>
      </body>
    </html>
  );
}
